version: '3.4'

services:
  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=New_Password123
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433
    volumes:
      - ./database-scripts:/docker-entrypoint-initdb.d
      - dbdata:/var/opt/mssql

  taskmaster:
    build:
      context: .
      dockerfile: TaskMaster/Dockerfile
    ports:
      - 8000:5000
    depends_on:
      - database
    environment:
      - ConnectionStrings__DefaultConnection=Server=database;Database=TaskMaster;User Id=sa;Password=New_Password123
      - DOTNET_URLS=http://+:5000

volumes:
  dbdata:
